@startuml


start

:Пользователь\nвыражает намерение\nперейти к контенту;

if (Система проверяет,\nдавал ли пользователь\nсогласие на соблюдение\nавторских прав) then (Нет)
    :Система предоставляет\nпользователю:\n* Информацию об условиях\nиспользования контента.\n* Возможность подтвердить\nсогласие на соблюдение\nавторских прав.;
else (Да)
    :Система дает\nпользователю\nдоступ к контенту;
    stop
endif

if (Пользователь дает согласие\nна соблюдение авторских прав) then (Нет)
    :Система **не** дает\nпользователю\nдоступ к контенту;
else (Да)
    :Система дает\nпользователю\nдоступ к контенту;
endif

stop

@enduml